apiVersion: v1
kind: Service
metadata:
  name: launchpad-loadbalancer
  namespace: {{ .Values.namespace }}
spec:
  type: LoadBalancer
  selector:
    app: launchpad
  ports:
    - port: {{ .Values.service.loadBalancer.port }}
      targetPort: 8080
