apiVersion: v1
kind: Service
metadata:
  name: launchpad-clusterip
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: launchpad
  ports:
    - port: {{ .Values.service.clusterIP.port }}
      targetPort: 8080
