apiVersion: apps/v1
kind: Deployment
metadata:
  name: launchpad-app
  namespace: launchpad-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: launchpad
  template:
    metadata:
      labels:
        app: launchpad
    spec:
      containers:
      - name: app
        image: 459532804090.dkr.ecr.us-east-1.amazonaws.com/launchpad-dev:run
        ports:
        - containerPort: 8080

        resources:
          requests:
            cpu: "25m"
            memory: "64Mi"
          limits:
            cpu: "100m"
            memory: "128Mi"

        # Commented out probes for Free Tier scheduling
        # readinessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 5
        #   periodSeconds: 10

        # livenessProbe:
        #   httpGet:
        #     path: /
        #     port: 8080
        #   initialDelaySeconds: 10
        #   periodSeconds: 20
