apiVersion: v1
kind: Service
metadata:
  name: launchpad-clusterip       # internal only
  namespace: launchpad-dev
spec:
  type: ClusterIP
  selector:
    app: launchpad
  ports:
    - port: 5000        # internal port
      targetPort: 8080  # container port
